### ISSUE TITLE
Losing MQTT connections

### ISSUE THREAD

**Issue by hi-flyer** [ssmall/bondhome-mqtt#4]
I have the software working but the connection to the broker drops after some period of time even though both the programs are running. the 2 programs I am talking about are:
/snap/go/6745/bin/go run main.go -broker tcp://localhost:1883 -bridge xxx -token yyy
/tmp/go-build829374078/b001/exe/main -broker tcp://localhost:1883 -bridge xxx -token yyy
as shown by ps ax

I am running on Ubuntu 20.04 and this condition appears to be associated with the automatic upgrades of APT. Do you have any insights (besides turning off automatic upgrades which I am testing now) on to how to prevent this disconnections?

thanks for any help.

**Comment by ssmall** [comment]
I'm happy to help as best I can! To start, can you provide some more details on how you are running the program? If you can include the application logs that would also be very helpful.

**Comment by hi-flyer** [comment]
ok, 
I have diverted the logs to a local file as I did not understand where they were going. I am running Ubuntu 20.04 although it was also happening under 18.04. 

I turned off the print line that said it was getting a status message from the bond hub every few minutes as that was not helpful to me (line 124 in bpup which now says //	log.Printf("Received UDP message from server: %q", string(buf[:n])) . 

I am running the application as a service. I did stop automatic ubuntu apt upgrades and the app seems to continue to work correctly until I do an upgrade at which time the app no longer pays attention to the the broker. 

The broker is nymead (local version on my home server which I use as my smarthome controller) which I have monitored the broker with mosquitto_sub which shows the message is being send  to the broker but the app ignores after the apt upgrade command. I have done ps ax after the apt upgrade and both of the previous mentioned apps (main.go & main) are still running and systemctl status bondhome-mqtt shows it is still running (that is what I labeled the service configuration file) even though the program is not doing anything after that. 

I also inserted in the startup a ping response every hour to insure that I out bound connectivity was working as I was losing that periodically (it ignored my local router giving the local computers ip addresses and was going out to the internet). It turned out that the docker install needed to be reinstalled to fix that problem. but I still check to make sure that was the problem.

missed something. in the log file the part that says Bond Hub to MQTT interface is running is based on pgrep of main.go request. on 2021/01/04 17:46:34 is where I start using your app as a service rather that running it locally and I also no longer used pgrep to check if the apps were running but used systemctl status to figure that out.

Think I have covered it all.
if there is a different log or mod you would like me to look at please indicate.
and thanks for the quick response. Your software is really appreciated. (ps I do not program in go and do not really understand the flow of the program. So if you need a change, please do not assume I know how to do that although I have programmed in several languages and can make the changes as directed).

[bondhome-mqtt.log](https://github.com/ssmall/bondhome-mqtt/files/5773540/bondhome-mqtt.log)

hopefully the drag and drop of the log file worked. Don't think it really shows anything but.

**Comment by ssmall** [comment]
Thank you for providing all that detail and for including the logs. Unfortunately, there was nothing obvious that I could see from the logs to indicate what the issue might be.

I'm not sure I'm fully understanding how you have everything configured -- from what I understand, you are running bondhome-mqtt as a systemctl service on the same Ubuntu host as your nymea instance (which is also your MQTT broker). Is that correct? If so, can you please share the systemctl service conf for the bondhome-mqtt service? It would also help to see any logs from the MQTT broker for the same time period.

I'm also not sure how `apt upgrade` is playing into the issue you're seeing. Could you be more specific about what `apt` commands you are running and their timing relative to when you see the loss of connectivity?

Sorry to keep asking for more details, but it sounds like there are a lot of moving parts involved here so the best I can do to help you solve the issue is try to understand precisely how everything is configured 😄

**Comment by hi-flyer** [comment]
First, ask all questions needed. I agree there are many moving parts.

Yes to the systemctl service. I have attached the service file. I also attached the startbondmqtt file I use with it and the old version I used before I started using the application as a service (startbondmqtt_old) ps I always use 1 after the startbondmqtt. they are in the compressed file. The date on the startbondmqtt_old file of 4 Jan 4 PM gives a hint of when I switched from running on my local account to a service. 

Nymea saves all logs in a sqlite database. I have extracted the logs to a csv file and compressed it (over 21 mb uncompressed). there are many actions in the logs having nothing to do with this problem but you can find the relevant ones by searching on bondhome (ok you probably can figure that out with no problem).

and again thank you for your help.
deleted
 
sorry forgot to answer one of your questions. My test is to send a command via the broker from nymea to open the blind and make sure it sends it by monitoring the log. Then I do sudo apt update and if there are updates, do sudo apt upgrade. Then send a command via nymea to open the blind while also monitoring the broker with mosquitto_sub to see if there is any action by your software. I see none even though before I did the upgrade there is commands sent to the bond hub. basically this process only takes a couple minutes. (I can do the sudo apt update and has no affect on your software). Your software has generally been running more than an hour on these tests.

**Comment by hi-flyer** [comment]
Think I have found the issue. I run needrestart on my system. generally speaking I accept the restarts. Unfortunately I do not pay enough attention to what it is restarting. 2 of the services it is restarting is goa-daemon and goa-identity-se which I suspect are the source of my problem. I am continuing to test and will let you know for sure.

**Comment by hi-flyer** [comment]
needrestart appears to be the issue. 
Thank you again for both the software and the help in trying to diagnose my problem. It is very much appreciated.

**Comment by ssmall** [comment]
Glad you were able to figure it out!
